/**
 * Self-host the site typefaces (DM Sans + Source Serif 4).
 *
 * Google Fonts serves woff2 only to modern user agents, so we ask with a Chrome
 * UA, keep the latin and latin-ext subsets, and rewrite the @font-face src to
 * point at the local copies. Self-hosting avoids a third-party connection on
 * every page load, which matters because these fonts are render-blocking.
 */
import fs from "node:fs";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = "hubfs/fonts/agm";
// Variable-weight ranges, so each family ships as a single file that covers
// every weight we use instead of one static file per weight.
// The range starts at 300 because the display headings are set light, which is
// what gives the reference site its editorial feel; at 400 they read too heavy.
const API =
  "https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300..700" +
  "&family=Source+Serif+4:opsz,wght@8..60,300..700" +
  "&display=swap";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

fs.mkdirSync(OUT_DIR, { recursive: true });

const css = await (await fetch(API, { headers: { "User-Agent": UA } })).text();

// Each block is preceded by a /* subset */ comment.
const blocks = [];
const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
let m;
while ((m = re.exec(css))) blocks.push({ subset: m[1], body: m[2] });

console.log(`fetched ${blocks.length} @font-face blocks`);

const out = [
  "/* AGM site typefaces, self-hosted.",
  " * DM Sans (SIL Open Font License 1.1): UI and body copy.",
  " * Source Serif 4 (SIL Open Font License 1.1): display headings.",
  " * Both are variable files covering weights 300-700.",
  " * Generated by tools/fetch-fonts.mjs; do not hand-edit.",
  " */",
  ""
];

let downloaded = 0;
for (const { subset, body } of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1] ?? "unknown";
  const weight = /font-weight:\s*([0-9 ]+)/.exec(body)?.[1].trim() ?? "400";
  const style = /font-style:\s*([a-z]+)/.exec(body)?.[1] ?? "normal";
  const url = /url\((https:\/\/[^)]+)\)/.exec(body)?.[1];
  if (!url) continue;

  const slug =
    family.toLowerCase().replace(/[^a-z0-9]+/g, "-") +
    `-${weight.replace(/\s+/g, "_")}-${style}-${subset}.woff2`;

  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  fs.writeFileSync(path.join(OUT_DIR, slug), buf);
  downloaded++;
  console.log(`  ${slug.padEnd(46)} ${(buf.length / 1024).toFixed(0)} KB`);

  out.push(body.replace(/url\(https:\/\/[^)]+\)/, `url(${slug})`).trim(), "");
}

fs.writeFileSync(path.join(OUT_DIR, "agm-fonts.css"), out.join("\n"));
console.log(`\nwrote ${OUT_DIR}/agm-fonts.css with ${downloaded} faces`);
